### PR TITLE
Fix bot author URLs

### LINKED ISSUE #478: user linking to a bot/app account creates an invalid link
octobox 255 2017-09-29 16-20-48

The link is linking to https://github.com/greenkeeper[bot] which doesn't exist, but *should* be linking to https://github.com/apps/greenkeeper

Additionally, albeit minor, but there is no space between the "name" and the "[bot]" part, which is a little strange.

### PR DESCRIPTION
**Pull request by chrisarcand**
Fixes #478

I left the author[bot] look because I think it's sort of nice to see that it's a bot; someone else is welcome to make it look prettier if they like.

### CODE REVIEW

File: app/models/subject.rb [hunk 1]
```diff
@@ -1,7 +1,20 @@
 class Subject < ApplicationRecord
   has_many :notifications, foreign_key: :subject_url, primary_key: :url
 
+  BOT_AUTHOR_REGEX = /\A(.*)\[bot\]\z/
+  private_constant :BOT_AUTHOR_REGEX
+
   def author_url
-    "#{Octobox.config.github_domain}/#{author}"
+    if bot_author?
+      "https://github.com/apps/#{BOT_AUTHOR_REGEX.match(author)[1]}"
```
Comment (chrisarcand) [inline app/models/subject.rb]: * This assumes that bot usernames directly match GitHub app names every time. I don't know if that's actually true or not.
* Hardcoded here - how does this affect GitHub Enterprise, etc? Can you get apps from other places? I don't know if this assumption is correct either.

@tarebyte Can you confirm any of this?

File: test/models/subject_test.rb [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
+
+class NotificationTest < ActiveSupport::TestCase
+  test 'author_url returns a user url with users' do
+    subject = create(:subject, author: "Fryguy")
+    assert_equal "https://github.com/Fryguy", subject.author_url
+  end
+
+  test 'author_url returns a GitHub apps URL with bots' do
+    subject = create(:subject, author: "greenfield[bot]")
+    assert_equal "https://github.com/apps/greenfield", subject.author_url
```
Comment (vitalkanev) [inline test/models/subject_test.rb]: Invalid link - gives `HTTP 404 - Not found`. It's seems to be a `greenkeeper`

Comment (chrisarcand) [reply test/models/subject_test.rb]: Hah, I forgot the name already. Fortunately this is just test so it doesn't really matter ^_^ I'll change it anyway, thanks.

File: app/models/subject.rb (hunk 1 above)
Comment (tarebyte) [reply app/models/subject.rb]: @chrisarcand at the moment GitHub Apps aren’t available in Enterprise. When it does ship it should point to their own instance, so let’s use configured domain for now.

Comment (chrisarcand) [reply app/models/subject.rb]: Excellent, thanks.

**Comment by andrew** [comment]
Seems like a crappy way for GitHub to shoehorn bot users into their existing API 😑
