### PR TITLE
fixes #1016 Cannot unarchive issues

### LINKED ISSUE #1016: Cannot unarchive issues
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

attempting to unarchive any issue in any way fails

### PR DESCRIPTION
**Pull request by prashuchaudhary**
* Added test case for Unarchive Notifications too.

### CODE REVIEW

**Comment by prashuchaudhary** [comment]
fixes #1016

File: app/models/notification.rb [hunk 1]
```diff
@@ -55,7 +55,7 @@ def state
   end
 
   def self.archive(notifications, value)
-    value = ActiveRecord::Type::Boolean.new.cast(value) || true
```
Comment (prashuchaudhary) [inline app/models/notification.rb]: `false || true => false`
