### PR TITLE
Handle GitHub API failures more elegantly on syncs

### LINKED ISSUE #310: Auto refresh fails when leaving a tab open
I haven't looked in to how auto refresh is actually implemented, so submitting this without knowing how easy or difficult it would be to fix.

I leave a Chrome tab pinned to Octobox all the time, and I imagine other people do as well. When I leave my machine for an extended period of time, I frequently come back to this in my pinned tab:

This is really irritating as not only do I have to reload the page, but I can't just reload it as the url isn't the actual path required to get me to my inbox. So I frequently trim off the path and access the page again. Seems unimportant, but doing it over and over and over again gets really old.

Note also that I use my own Octobox hosted with Heroku, so maybe my dyno is falling asleep and this doesn't occur on octobox.io or other hosted scenarios that don't do that sort of thing? I would suggest we still address it if possible as I'm sure plenty of people would love to continue hosting this on their hobby tier Heroku without this issue.

### PR DESCRIPTION
**Pull request by chrisarcand**
Closes #310, I'm fairly certain.

Like we do with the sync task, we should be catching API errors from GitHub and reporting on it, not falling apart and responding with a 500 error.

### CODE REVIEW

File: test/controllers/notifications_controller_test.rb [hunk 1]
```diff
@@ -239,6 +239,23 @@ class NotificationsControllerTest < ActionDispatch::IntegrationTest
     assert_response :ok
   end
 
+  test 'gracefully handles failed user notification syncs' do
+    sign_in_as(@user)
+    User.any_instance.stubs(:sync_notifications).raises(Octokit::BadGateway)
```
Comment (chrisarcand) [inline test/controllers/notifications_controller_test.rb]: The use of `any_instance` here makes me cringe, but alas it's how we're doing other such specs.

We should refactor the test helper a bit and see about allowing an actual user object to be passed to avoid this but leaving it for now.

File: app/controllers/notifications_controller.rb [hunk 2]
```diff
@@ -184,6 +184,12 @@ def sync
       format.html { redirect_back fallback_location: root_path }
       format.json { head :ok }
     end
+  rescue Octokit::BadGateway, Octokit::ServiceUnavailable
```
Comment (tarebyte) [inline app/controllers/notifications_controller.rb]: What do you think about adding the real error to the server log?

Comment (chrisarcand) [reply app/controllers/notifications_controller.rb]: Losing it from the log is certainly silly, good catch. 👍

**Comment by andrew** [comment]
🚢 on https://octobox.io
